### ISSUE TITLE
Add Solus package

### ISSUE THREAD

**Issue by georgybog** [borgbase/vorta.borgbase.com#13]
Command for install sudo eopkg it vorta

https://dev.getsol.us/source/vorta/

Maintained by [kyrios123](https://github.com/kyrios123/)

**Comment by m3nu** [comment]
New or existing Linux packages and maintainers should go there: https://vorta.borgbase.com/download/linux/

**Comment by kyrios123** [comment]
> @kyrios123 are you still maintaining it? If you are I recommend updating it to 0.6.26 now, and 0.7.1 when it comes out. Don't upgrade it to 0.7.0, its currently slightly broken.

There is no official maintainer for this package at the moment, but no worry I just updated it to 0.7.1
Thanks for this great softwae by the way :+1: 

@georgybog packages with official maintainers have a `MAINTAINERS.md` file in the root of their repository (like [here](https://dev.getsol.us/source/linux-tools/) for example).

**Comment by samuel-w** [comment]
The dependencies are incorrect I think:
python-keyring and python-qdarkstyle are no longer dependencies.
python-secretstorage and python-setuptools are now dependencies.

For reference:
https://github.com/borgbase/vorta/blob/9cc23de6bc05b0c40c304bb673e6561c0887fc8f/setup.cfg

**Comment by kyrios123** [comment]
Thanks for pointing this !
