### ISSUE TITLE
Documentation for Filter Syntax

### ISSUE THREAD

**Issue by jetchirag** [borgbase/vorta.borgbase.com#45]
We'll need to update documentation to explain filtering options (https://github.com/borgbase/vorta/pull/1749). I think we can add a link to the documentation beside the search icon. Where should the syntax go?

**Comment by m3nu** [comment]
If possible, a feature should explain itself. Very few people will read the docs, unless truly a lot of background explaining is needed.

**Comment by jetchirag** [comment]
I would want that too but not sure how to go about it. The syntax is not
standard and would require do to see what does what.

Though, Normal search which doesn't require any syntax would be enough for
most use case. Do we need to add an interactive dialog to select filtering
option?

**Comment by m3nu** [comment]
Right. The syntax will need explaining. How long is that? Would that be a table or list or something?

**Comment by jetchirag** [comment]
I was thinking to make it similar to a man page.

This is the original syntax, final one is a bit modified.

```
[ string ] [ -m ] [ -i ] [ -p ] [ -c ] [ -s ]
Note: Search String and other options are all optional

Options/Flags:

	--match -m <type>
	Type of match query
	Supported values:
		in (default): Filename should contain search string
		exact: Filename must match the search string exactly
		re: Use regex to match filename    

	--ignore-case -i
	Ignore Case. Supported by `in` and `exact` match type only.	

	--path -p <path>
	Specify path to match. Supports wildcard. Parsed using glob (?)
	Example:
		--path /home/vorta/Documents
		--path /var/www/public/*
		--path */src/*
	
	--change -c <type>
	Only available in Diff View. Supported values:
		A: Match only Added files
		R: Match only Removed files
		...
	
	--size -s <relation[<|>]number[B|KB|MB|GB>]>
	Match by size. Can be combined once to create a range. Range must be bounded.
	Example:
		--size <10MB
		--size >1GB
		--size >1GB --size <10GB
```

**Comment by m3nu** [comment]
Since the docs are in markdown and Vorta isn't a CLI app, I'd suggest sticking to normal markdown format. Also to avoid anyone mistaking this syntax for actual CLI args. Something like:

---

### Supported search parameters

#### Match by size
Can be combined once to create a range. Range must be bounded.

Examples:
- `--size <10MB`

**Comment by real-yfprojects** [comment]
A table might be quicker to read and find options in.

**Comment by real-yfprojects** [comment]
I would add a new page under `Usage` for this documentation.
